### ISSUE TITLE
Where to put the Sass::Plugin.options[:debug_info] = true ?

### ISSUE THREAD

**Issue by tordans** [nex3/firesass#1]
Hi!

You write 
"If you're using Sass with a Ruby web framework, you probably want to do: Sass::Plugin.options[:debug_info] = true"

But where do I put this line of configuration?

And btw, which version is "the development"-version? Is haml-3.0.1 fine? Otherwise: How do I install the dev-version?

Thanks, the plugin is a great idea!

Tobias

**Comment by nex3** [comment]
It depends a little on the Ruby framework you're using. If you're using Rails, put it in `config/environment.rb`; otherwise, either put it in `config.ru` or wherever else configuration is specified.

haml-3.0.\* is fine. Since Haml/Sass 3 have been released, a development version is no longer necessary.

I've updated the README to better address these issues.
