### ISSUE TITLE
FireSass future

### ISSUE THREAD

**Issue by thany** [nex3/firesass#24]
So what's going to happen? The last commit was more than a year ago, and as it stands, FireSass simply doesn't work anymore since Firefox and Firebug haven gotten more than a couple of updates.

If this project is truly stalled, then I propose this plugin be removed from the Extension repository for Firefox, or set it to a maximum supported version of, say, Firefox 27. Folks will keep installing this broken plugin if this doesn't happen. And it would be a shame to have this plugin "rot" away - better to border its parameters now that it's still relatively possible.

That, or someone might feel inclined to take over or fork this project and fix the things that need fixing and add to or replace the Extension at Mozilla's repo.

**Comment by nex3** [comment]
This is no longer being maintained. Source maps are now the official means of associating Sass input with SCSS output, so it doesn't make sense to put a lot of effort into what was from the beginning kind of a hack. I've disabled the add-on in the Mozilla repository.

**Comment by AlmogBaku** [comment]
hey!, why did you disable this plugin? it works great!
How can I use this functionality now? is there alternative.

**Comment by mdrmike** [comment]
Ya, it would be nice if this were available for testing/debugging on older browsers, but FWIW, I imagine the rationale to disable is because support for sourcemap files (*.js.map, *.css.map) is builtin to all new browser development tools. Firefox, chromium, even IE11 all support sourcemaps. 

Check out: https://hacks.mozilla.org/2014/02/live-editing-sass-and-less-in-the-firefox-developer-tools/

To generate sass/scss sourcemap files requires  sass 3.3+ or compass 1.0.1+

to check versions:  gem list
to update: gem update

**Comment by ricardozea** [comment]
The problem with SourceMaps is that if you're using Prepros (http://alphapixels.com/prepros/) to compile your SCSS files, when you select the option to use SourceMaps, Autoprefixer can't be used. See attached image at the bottom.

This has quite an impact for me (not sure if others are experiencing the same issue) because that means going back to using Compass (which I was only using to deal with vendor prefixing) or try using one of the text editors plugins, https://github.com/postcss/autoprefixer#text-editors.

So being able to use this extension is still quite a valuable asset.

FWIW, you can download FireSass .xpi file from my Google Drive share since you can't download from anywhere else on the web anymore: https://docs.google.com/file/d/0B3S7H2H7meSUdjBLWUpWd1BQaTg/

Prepros: Autoprefixer doesn't work with SourceMaps
![cccc screenshot - 9_12_2014 2_41_04 pm](https://cloud.githubusercontent.com/assets/1656481/4254520/70cd0784-3aac-11e4-98ff-2f04cdd078c3.png)
